# Generated by Django 3.2 on 2022-02-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_post_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='rasm',
            new_name='image',
        ),
    ]
